### ISSUE TITLE
HTML Special characters

### ISSUE THREAD

**Issue by martoio** [kylaking/prj-rev-bwfs-dasmoto#1]
Check out this article that explains why you need to care about using special characters in HTML: http://text-symbols.com/html/encode/
The ampersand should be written as:
``&amp;``

https://github.com/kylaking/prj-rev-bwfs-dasmoto/blob/44763692b8443ea9529c7e061e02d0d27c2a2404/Dasmoto/index.html#L12

**Comment by kylaking** [comment]
Noted!
