### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by martoio** [kylaking/prj-rev-bwfs-dasmoto#3]
Make sure you add the ``alt`` attribute to your images to maintain accessibility for all audiences of the page (particularly visually-impaired users). Remember to add it even in these simple projects and it will become a habit. (Hint: as long as you have the ``alt`` attribute with something semi-meaningful, we'll be happy with it).
For more info: https://www.codecademy.com/articles/accessibility

https://github.com/kylaking/prj-rev-bwfs-dasmoto/blob/44763692b8443ea9529c7e061e02d0d27c2a2404/Dasmoto/index.html#L18

**Comment by kylaking** [comment]
Yes! Great reminder. Thanks.
